### ISSUE TITLE
Create routes to allow the Mobile and Client to access the api. 

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-web-api#26]
## The Issue
This issue builds in links to be able to CRUD data from the database, this will have routes that will allow users to access and change information from the client app and the mobile app. 

### To-do
- [x] Bills
  - [x] Allow a `user` to create a bill.
  - [x] Allow a `user` to assign the bill to other users.
  - [x] A `user` should be able to see the bill that are associated with them. 
  - [x] A `user` should be able to accept a bill associated with them.
  - [x] A `user` should be able to pay a bill associated with them. 

- [x] Apartments
  - [x] Allow a `user` to create an `apartment`.
  - [x] Allow a `user` to join the `apartment`.
  - [x] A `user` should be able to view details of the `apartment`. 
  - [x] A `user` should be able to leave an `apartment`
  - [x] A `associated user` should be able to delete the apartment.
