### ISSUE TITLE
Add a DB of payment methods

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-web-api#29]
---
name: Feature request
about: Add a feature that is a part of the development pipeline
title: ""
labels: "enhancement"
assignees: ""
---

# Feature Request

_Use this form to outline potential new features or planned features in Lofft_

**[Notion Link]()**

---

## Feature description
The addition of payment methods needs to be created to the database, this should have a relationship to a user, and only store the type, method (this maybe only temp until an API is used to handle payments.)"

### Feature experience

- A `User` can see which payment methods they have.

### Todo

- [ ] Build the migration
- [ ] Write a model with a relation to User
- [ ] Fields -> Payment Method, User, Active
